### ISSUE TITLE
use proper commit message

### ISSUE THREAD

**Issue by OlivierJM** [YonaMiti/ALC-4.0#1]
Hi @YonaMiti,

Awesome work you are doing there 💪🏾🚀

Commit messages are meant to describe an accomplishment of what you have achieved, this helps you in the future determine what you were doing at the specific moment and it makes it easy very easy to roll back to that version of the project.
I looked at the commit messages and they all say this is new code, if you can start making them more specific.

**Comment by YonaMiti** [comment]
Hi OlivierWill do that next time second time using it from the time you were teaching LOLOn 15 Jul 2019 09:55, Olivier JM <notifications@github.com> wrote:Hi @YonaMiti,

Awesome work you are doing there 💪🏾🚀

Commit messages are meant to describe an accomplishment of what you have achieved, this helps you in the future determine what you were doing at the specific moment and it makes it easy very easy to roll back to that version of the project.

I looked at the commit messages and they all say this is new code, if you can start making them more specific.

**Comment by OlivierJM** [comment]
Alright, looking forward to see better commit messages.
